"""Add scraping model

Revision ID: 001268db4821
Revises: 5bc15e3b1870
Create Date: 2026-02-25 13:43:22.015780

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001268db4821"
down_revision: str | Sequence[str] | None = "5bc15e3b1870"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scrapings_id"), table_name="scrapings")
    op.drop_table("scrapings")
    op.alter_column(
        "subscription_changes",
        "change_type",
        existing_type=postgresql.ENUM(
            "upgrade", "downgrade", "signup", "expire", name="changetype"
        ),
        nullable=False,
    )
    op.alter_column(
        "subscription_changes",
        "source",
        existing_type=postgresql.ENUM("user", "admin", "system", name="changesource"),
        nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "status",
        existing_type=postgresql.ENUM(
            "active",
            "trailing",
            "canceled",
            "expired",
            "pending_payment",
            name="subscriptionstatus",
        ),
        nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "source",
        existing_type=postgresql.ENUM(
            "free", "stripe", "admin", name="subscriptionsource"
        ),
        nullable=False,
    )
    op.alter_column(
        "user_profiles",
        "risk_bucket",
        existing_type=postgresql.ENUM(
            "no_risk",
            "conservative",
            "balanced",
            "aggressive",
            "risk_averse",
            "moderate",
            "moderately_aggressive",
            "very_aggressive",
            name="riskbucket",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profiles",
        "risk_bucket",
        existing_type=postgresql.ENUM(
            "no_risk",
            "conservative",
            "balanced",
            "aggressive",
            "risk_averse",
            "moderate",
            "moderately_aggressive",
            "very_aggressive",
            name="riskbucket",
        ),
        nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "source",
        existing_type=postgresql.ENUM(
            "free", "stripe", "admin", name="subscriptionsource"
        ),
        nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "status",
        existing_type=postgresql.ENUM(
            "active",
            "trailing",
            "canceled",
            "expired",
            "pending_payment",
            name="subscriptionstatus",
        ),
        nullable=True,
    )
    op.alter_column(
        "subscription_changes",
        "source",
        existing_type=postgresql.ENUM("user", "admin", "system", name="changesource"),
        nullable=True,
    )
    op.alter_column(
        "subscription_changes",
        "change_type",
        existing_type=postgresql.ENUM(
            "upgrade", "downgrade", "signup", "expire", name="changetype"
        ),
        nullable=True,
    )
    op.create_table(
        "scrapings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("scrapings_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("scrapings_pkey")),
    )
    op.create_index(op.f("ix_scrapings_id"), "scrapings", ["id"], unique=False)
    # ### end Alembic commands ###
