"""Add onboarding questions

Revision ID: 072fb12742fe
Revises: 75ac8fa8a1b2
Create Date: 2026-01-24 13:18:22.352592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072fb12742fe'
down_revision: Union[str, Sequence[str], None] = '75ac8fa8a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('validation_rules', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_questions_id'), 'onboarding_questions', ['id'], unique=False)
    op.create_table('user_onboarding_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['onboarding_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_onboarding_answers_id'), 'user_onboarding_answers', ['id'], unique=False)
    op.drop_index(op.f('ix_subscription_changes_id'), table_name='subscription_changes')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_changes_id'), 'subscription_changes', ['id'], unique=False)
    op.drop_index(op.f('ix_user_onboarding_answers_id'), table_name='user_onboarding_answers')
    op.drop_table('user_onboarding_answers')
    op.drop_index(op.f('ix_onboarding_questions_id'), table_name='onboarding_questions')
    op.drop_table('onboarding_questions')
    # ### end Alembic commands ###
