"""change_ingested_pdf_id_to_uuid

Revision ID: 10978ad49e78
Revises: 39bae3211c3e
Create Date: 2026-03-27 17:03:41.889746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10978ad49e78'
down_revision: Union[str, Sequence[str], None] = '39bae3211c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Note: Enum changes (HOURLY -> DAILY) and data migration 
    # are handled in a separate script before this migration.
    
    # 1. IngestedPDF id change to UUID
    # Add temporary UUID column
    op.add_column('ingested_pdfs', sa.Column('id_uuid', sa.UUID(), nullable=True))
    
    # Fill the new column with random UUIDs using Python
    connection = op.get_bind()
    results = connection.execute(sa.text("SELECT id FROM ingested_pdfs")).fetchall()
    
    import uuid
    for row in results:
        new_uuid = str(uuid.uuid4())
        connection.execute(
            sa.text("UPDATE ingested_pdfs SET id_uuid = :uuid WHERE id = :id"),
            {"uuid": new_uuid, "id": row[0]}
        )
    
    # Drop the primary key constraint and existing id column
    op.execute('ALTER TABLE ingested_pdfs DROP CONSTRAINT IF EXISTS ingested_pdfs_pkey CASCADE')
    op.drop_index('ix_ingested_pdfs_id', table_name='ingested_pdfs')
    op.drop_column('ingested_pdfs', 'id')
    
    # 2. Rename new column to 'id', make it non-nullable, and set as primary key
    op.alter_column('ingested_pdfs', 'id_uuid', new_column_name='id')
    # op.rename_column('ingested_pdfs', 'id_uuid', 'id') # Not supported in all op versions
    op.alter_column('ingested_pdfs', 'id', nullable=False)
    op.create_primary_key('ingested_pdfs_pkey', 'ingested_pdfs', ['id'])
    op.create_index(op.f('ix_ingested_pdfs_id'), 'ingested_pdfs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ingested_pdfs_pkey', 'ingested_pdfs', type_='primary')
    op.drop_index('ix_ingested_pdfs_id', table_name='ingested_pdfs')
    op.drop_column('ingested_pdfs', 'id')
    
    op.add_column('ingested_pdfs', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=True))
    op.execute('CREATE SEQUENCE ingested_pdfs_id_seq')
    op.execute("UPDATE ingested_pdfs SET id = nextval('ingested_pdfs_id_seq')")
    op.alter_column('ingested_pdfs', 'id', nullable=False)
    op.create_primary_key('ingested_pdfs_pkey', 'ingested_pdfs', ['id'])
    op.create_index(op.f('ix_ingested_pdfs_id'), 'ingested_pdfs', ['id'], unique=False)
