"""remove stripe columns

Revision ID: 25ee26d1576b
Revises: 8d84464ce929
Create Date: 2026-07-02 09:26:30.640315

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "25ee26d1576b"
down_revision: str | Sequence[str] | None = "8d84464ce929"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stripe_customers_id"), table_name="stripe_customers")
    op.drop_index(
        op.f("ix_stripe_customers_stripe_customer_id"), table_name="stripe_customers"
    )
    op.drop_table("stripe_customers")
    op.drop_column("subscriptions", "stripe_subscription_id")
    op.drop_constraint(op.f("tiers_stripe_price_id_key"), "tiers", type_="unique")
    op.drop_constraint(
        op.f("tiers_stripe_yearly_price_id_key"), "tiers", type_="unique"
    )
    op.drop_column("tiers", "stripe_price_id")
    op.drop_column("tiers", "stripe_product_id")
    op.drop_column("tiers", "stripe_yearly_price_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tiers",
        sa.Column(
            "stripe_yearly_price_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "tiers",
        sa.Column(
            "stripe_product_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "tiers",
        sa.Column("stripe_price_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint(
        op.f("tiers_stripe_yearly_price_id_key"),
        "tiers",
        ["stripe_yearly_price_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("tiers_stripe_price_id_key"),
        "tiers",
        ["stripe_price_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "stripe_subscription_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.create_table(
        "stripe_customers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "stripe_customer_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("stripe_customers_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("stripe_customers_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("stripe_customers_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_stripe_customers_stripe_customer_id"),
        "stripe_customers",
        ["stripe_customer_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_stripe_customers_id"), "stripe_customers", ["id"], unique=False
    )
    # ### end Alembic commands ###
