"""add tier models

Revision ID: 25f156f48506
Revises: 4647d8eb4805
Create Date: 2026-01-01 18:38:39.801308

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25f156f48506"
down_revision: str | Sequence[str] | None = "4647d8eb4805"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entitlements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entitlements_id"), "entitlements", ["id"], unique=False)
    op.create_table(
        "tiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tiers_id"), "tiers", ["id"], unique=False)
    op.create_table(
        "tier_entitlements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tier_id", sa.Integer(), nullable=True),
        sa.Column("entitlement_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entitlement_id"],
            ["entitlements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tier_id"],
            ["tiers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tier_entitlements_id"), "tier_entitlements", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tier_entitlements_id"), table_name="tier_entitlements")
    op.drop_table("tier_entitlements")
    op.drop_index(op.f("ix_tiers_id"), table_name="tiers")
    op.drop_table("tiers")
    op.drop_index(op.f("ix_entitlements_id"), table_name="entitlements")
    op.drop_table("entitlements")
    # ### end Alembic commands ###
