"""add_verification_token_and_is_verified

Revision ID: 2e39d12f2d43
Revises: 48ed81ed6821
Create Date: 2026-05-04 16:34:02.597842

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e39d12f2d43"
down_revision: str | Sequence[str] | None = "48ed81ed6821"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_verification_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("token_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_verification_tokens_id"),
        "user_verification_tokens",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_verification_tokens_token"),
        "user_verification_tokens",
        ["token"],
        unique=True,
    )
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_verified = FALSE")
    op.alter_column("users", "is_verified", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    op.drop_index(
        op.f("ix_user_verification_tokens_token"), table_name="user_verification_tokens"
    )
    op.drop_index(
        op.f("ix_user_verification_tokens_id"), table_name="user_verification_tokens"
    )
    op.drop_table("user_verification_tokens")
    # ### end Alembic commands ###
