"""add_scraping_job_history

Revision ID: 39bae3211c3e
Revises: b2c3d4e5f6g7
Create Date: 2026-03-25 13:00:56.349241

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39bae3211c3e"
down_revision: str | Sequence[str] | None = "b2c3d4e5f6g7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("modules", "course_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("modules", "course_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
