"""add_lesson_resource_and_expand_subtitles

Revision ID: 3bcb59298ce5
Revises: 78903489063d
Create Date: 2026-03-02 16:12:47.047555

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bcb59298ce5"
down_revision: str | Sequence[str] | None = "78903489063d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lesson_resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "lesson_subtitles", "lesson_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "lesson_subtitles",
        "language",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    op.alter_column(
        "lesson_subtitles", "file_url", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lesson_subtitles", "file_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "lesson_subtitles",
        "language",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
    )
    op.alter_column(
        "lesson_subtitles", "lesson_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_table("lesson_resources")
    # ### end Alembic commands ###
