"""updated course and course version table

Revision ID: 48ed81ed6821
Revises: c683546cb6d2
Create Date: 2026-04-30 07:32:33.076255

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48ed81ed6821"
down_revision: str | Sequence[str] | None = "c683546cb6d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_course_versions_course"), "course_versions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "course_versions", "courses", ["course_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("fk_lesson_progress_lesson"), "lesson_progress", type_="foreignkey"
    )
    op.create_foreign_key(None, "lesson_progress", "lessons", ["lesson_id"], ["id"])
    op.drop_constraint(
        op.f("fk_lesson_resources_lesson"), "lesson_resources", type_="foreignkey"
    )
    op.create_foreign_key(None, "lesson_resources", "lessons", ["lesson_id"], ["id"])
    op.drop_constraint(
        op.f("fk_lesson_subtitles_lesson"), "lesson_subtitles", type_="foreignkey"
    )
    op.create_foreign_key(None, "lesson_subtitles", "lessons", ["lesson_id"], ["id"])
    op.alter_column(
        "scraping_sub_url", "document_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_unique_constraint(None, "scraping_sub_url", ["document_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scraping_sub_url", type_="unique")
    op.alter_column(
        "scraping_sub_url", "document_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(None, "lesson_subtitles", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_lesson_subtitles_lesson"),
        "lesson_subtitles",
        "lessons",
        ["lesson_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "lesson_resources", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_lesson_resources_lesson"),
        "lesson_resources",
        "lessons",
        ["lesson_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "lesson_progress", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_lesson_progress_lesson"),
        "lesson_progress",
        "lessons",
        ["lesson_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "course_versions", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_course_versions_course"),
        "course_versions",
        "courses",
        ["course_id"],
        ["id"],
    )
    # ### end Alembic commands ###
