"""update_user_sessions

Revision ID: 53b599f1af7f
Revises: d7d4facb106d
Create Date: 2026-01-01 12:54:05.479306

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53b599f1af7f"
down_revision: str | Sequence[str] | None = "d7d4facb106d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_sessions", sa.Column("token_hash", sa.String(), nullable=False))
    op.add_column(
        "user_sessions", sa.Column("expires_at", sa.DateTime(), nullable=False)
    )
    op.add_column("user_sessions", sa.Column("revoked", sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, "user_sessions", ["token_hash"])
    op.drop_column("user_sessions", "expires")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sessions",
        sa.Column(
            "expires", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint("user_sessions_token_hash_key", "user_sessions", type_="unique")
    op.drop_column("user_sessions", "revoked")
    op.drop_column("user_sessions", "expires_at")
    op.drop_column("user_sessions", "token_hash")
    # ### end Alembic commands ###
