"""Add broker models

Revision ID: 57c7a26720e3
Revises: ae0e7f804d1f
Create Date: 2026-01-20 12:52:17.766302

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57c7a26720e3"
down_revision: str | Sequence[str] | None = "ae0e7f804d1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brokers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("redirect_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brokers_id"), "brokers", ["id"], unique=False)
    op.create_table(
        "broker_clicks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("broker_id", sa.Integer(), nullable=False),
        sa.Column(
            "clicked_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["brokers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_broker_clicks_id"), "broker_clicks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_broker_clicks_id"), table_name="broker_clicks")
    op.drop_table("broker_clicks")
    op.drop_index(op.f("ix_brokers_id"), table_name="brokers")
    op.drop_table("brokers")
    # ### end Alembic commands ###
