"""Update chat models

Revision ID: 5bc15e3b1870
Revises: 649e6e771593
Create Date: 2026-02-13 13:18:08.652678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc15e3b1870'
down_revision: Union[str, Sequence[str], None] = '649e6e771593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('chat_messages', sa.Column('role', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('model', sa.String(), nullable=True))
    op.execute("UPDATE chat_messages SET role = sender")
    op.execute("UPDATE chat_sessions SET model = 'standard'")
    op.alter_column('chat_messages', 'role', nullable=False)
    op.alter_column('chat_sessions', 'model', nullable=False)
    op.drop_column('chat_messages', 'sender')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'model')
    op.add_column('chat_messages', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chat_messages', 'role')
    # ### end Alembic commands ###
