"""Add scraping_sub_url table

Revision ID: 600e34347c56
Revises: 6c1425d1206b
Create Date: 2026-03-12 18:26:09.428124

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "600e34347c56"
down_revision: str | Sequence[str] | None = "6c1425d1206b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
