"""Add title to chat_sessions

Revision ID: 649e6e771593
Revises: e01b2b9ce6be
Create Date: 2026-02-10 13:55:54.660214

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "649e6e771593"
down_revision: str | Sequence[str] | None = "e01b2b9ce6be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_sessions", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_sessions", "title")
    # ### end Alembic commands ###
