"""add_indices_to_onboarding_answers

Revision ID: 6963fe5e4926
Revises: dbcc1e8f7f8b
Create Date: 2026-01-29 17:08:47.366242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6963fe5e4926'
down_revision: Union[str, Sequence[str], None] = 'dbcc1e8f7f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_onboarding_answers_option_id'), 'user_onboarding_answers', ['option_id'], unique=False)
    op.create_index(op.f('ix_user_onboarding_answers_question_id'), 'user_onboarding_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_onboarding_answers_question_id'), table_name='user_onboarding_answers')
    op.drop_index(op.f('ix_user_onboarding_answers_option_id'), table_name='user_onboarding_answers')
    # ### end Alembic commands ###
