"""create subscription tables

Revision ID: 6c4a8f2e1b3d
Revises: 25f156f48506
Create Date: 2026-01-22 18:53:30.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4a8f2e1b3d'
down_revision: Union[str, Sequence[str], None] = '25f156f48506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'trailing', 'canceled', 'expired', 'pending_payment', name='subscriptionstatus'), nullable=True),
    sa.Column('source', sa.Enum('free', 'stripe', 'admin', name='subscriptionsource'), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)

    op.create_table('subscription_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('previous_tier_id', sa.Integer(), nullable=True),
    sa.Column('new_tier_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.Enum('upgrade', 'downgrade', name='changetype'), nullable=True),
    sa.Column('source', sa.Enum('user', 'admin', 'system', name='changesource'), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_changes_id'), 'subscription_changes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_changes_id'), table_name='subscription_changes')
    op.drop_table('subscription_changes')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')

    # Drop types explicitly to clean up for Postgres
    op.execute("DROP TYPE IF EXISTS changetype")
    op.execute("DROP TYPE IF EXISTS changesource")
    op.execute("DROP TYPE IF EXISTS subscriptionstatus")
    op.execute("DROP TYPE IF EXISTS subscriptionsource")
    # ### end Alembic commands ###
