"""add_yearly_pricing_to_tiers

Revision ID: 75ac8fa8a1b2
Revises: f726ef933fa6
Create Date: 2026-01-21 15:07:53.218891

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75ac8fa8a1b2"
down_revision: str | Sequence[str] | None = "f726ef933fa6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tiers", sa.Column("price_amount_yearly", sa.Integer(), nullable=True)
    )
    op.add_column(
        "tiers", sa.Column("stripe_yearly_price_id", sa.String(), nullable=True)
    )
    op.create_unique_constraint(None, "tiers", ["stripe_yearly_price_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tiers_stripe_yearly_price_id_key", "tiers", type_="unique")
    op.drop_column("tiers", "stripe_yearly_price_id")
    op.drop_column("tiers", "price_amount_yearly")
    # ### end Alembic commands ###
