"""update_course_models

Revision ID: 78903489063d
Revises: 001268db4821
Create Date: 2026-03-02 15:09:40.463460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78903489063d'
down_revision: Union[str, Sequence[str], None] = '001268db4821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('course_image', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('lesson_progress', sa.Column('duration_done', sa.Integer(), nullable=True))
    op.add_column('lesson_progress', sa.Column('last_position', sa.Integer(), nullable=True))
    op.add_column('lesson_progress', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # lesson_subtitles was never created in a prior migration — create it here
    op.create_table(
        'lesson_subtitles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lesson_id', sa.Integer(), nullable=True),
        sa.Column('language', sa.String(length=10), nullable=True),
        sa.Column('label', sa.String(length=100), nullable=True),
        sa.Column('file_url', sa.String(), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lessons', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('is_preview', sa.Boolean(), nullable=True))
    op.add_column('lessons', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Handle NOT NULL 'order' column in lessons
    op.add_column('lessons', sa.Column('order', sa.Integer(), nullable=True))
    op.execute('UPDATE lessons SET "order" = 0')
    op.alter_column('lessons', 'order', nullable=False)

    op.add_column('modules', sa.Column('description', sa.Text(), nullable=True))
    
    # Handle NOT NULL 'order' column in modules
    op.add_column('modules', sa.Column('order', sa.Integer(), nullable=True))
    op.execute('UPDATE modules SET "order" = 0')
    op.alter_column('modules', 'order', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'order')
    op.drop_column('modules', 'description')
    op.drop_column('lessons', 'order')
    op.drop_column('lessons', 'extra_data')
    op.drop_column('lessons', 'is_preview')
    op.drop_column('lessons', 'description')
    op.drop_table('lesson_subtitles')
    op.drop_column('lesson_progress', 'completed_at')
    op.drop_column('lesson_progress', 'last_position')
    op.drop_column('lesson_progress', 'duration_done')
    op.drop_column('courses', 'updated_at')
    op.drop_column('courses', 'estimated_duration')
    op.drop_column('courses', 'course_image')
    op.drop_column('courses', 'description')
    # ### end Alembic commands ###
