"""added subscription model

Revision ID: 7d300b47e465
Revises: 6c4a8f2e1b3d
Create Date: 2026-01-02 18:58:06.632237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d300b47e465'
down_revision: Union[str, Sequence[str], None] = '6c4a8f2e1b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('pending_tier_id', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('pending_started_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tiers_level'), 'tiers', ['level'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiers_level'), table_name='tiers')
    op.drop_column('subscriptions', 'pending_started_at')
    op.drop_column('subscriptions', 'pending_tier_id')
    # ### end Alembic commands ###
