"""remove user_id from scraping_url

Revision ID: 9b484965686c
Revises: 10978ad49e78
Create Date: 2026-04-10 15:01:34.630753

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b484965686c"
down_revision: str | Sequence[str] | None = "10978ad49e78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_constraint(
        op.f("scrapping_url_user_id_fkey"), "scrapping_url", type_="foreignkey"
    )
    op.drop_column("scrapping_url", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scrapping_url",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("scrapping_url_user_id_fkey"),
        "scrapping_url",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_table(
        "scrapings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("scrapings_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("scrapings_pkey")),
    )
    op.create_index(op.f("ix_scrapings_id"), "scrapings", ["id"], unique=False)
    # ### end Alembic commands ###
