"""add missing columns to tiers and subscriptions

Revision ID: a81c3b61fdd9
Revises: fae09c51fe97
Create Date: 2026-01-09 13:29:52.038257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81c3b61fdd9'
down_revision: Union[str, Sequence[str], None] = 'fae09c51fe97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('tiers', sa.Column('price_amount', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tiers', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('tiers', sa.Column('stripe_product_id', sa.String(), nullable=True))
    op.add_column('tiers', sa.Column('stripe_price_id', sa.String(), nullable=True))
    op.add_column('tiers', sa.Column('highlights', sa.JSON(), nullable=True))
    op.add_column('tiers', sa.Column('is_popular', sa.Boolean(), nullable=True))
    op.add_column('tiers', sa.Column('icon', sa.String(), nullable=True))
    op.alter_column('tiers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tiers', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'tiers', ['stripe_product_id'])
    op.create_unique_constraint(None, 'tiers', ['stripe_price_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tiers_stripe_price_id_key', 'tiers', type_='unique')
    op.drop_constraint('tiers_stripe_product_id_key', 'tiers', type_='unique')
    op.alter_column('tiers', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tiers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tiers', 'icon')
    op.drop_column('tiers', 'is_popular')
    op.drop_column('tiers', 'highlights')
    op.drop_column('tiers', 'stripe_price_id')
    op.drop_column('tiers', 'stripe_product_id')
    op.drop_column('tiers', 'currency')
    op.drop_column('tiers', 'price_amount')
    # op.drop_column('subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###
