"""add document_id to scraping_sub_url

Revision ID: b74fcab99764
Revises: 9b484965686c
Create Date: 2026-04-15 12:08:55.810040

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b74fcab99764"
down_revision: str | Sequence[str] | None = "9b484965686c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scraping_sub_url", sa.Column("document_id", sa.UUID(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scraping_sub_url", "document_id")
    # ### end Alembic commands ###
