"""add document_id to scraping_sub_url

Revision ID: b74fcab99764
Revises: 9b484965686c
Create Date: 2026-04-15 12:08:55.810040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74fcab99764'
down_revision: Union[str, Sequence[str], None] = '9b484965686c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_sub_url', sa.Column('document_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_sub_url', 'document_id')
    # ### end Alembic commands ###
