"""remove unique constraint from stripe_product_id

Revision ID: c28907b9cd9e
Revises: a81c3b61fdd9
Create Date: 2026-01-10 22:41:45.048255

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c28907b9cd9e"
down_revision: str | Sequence[str] | None = "a81c3b61fdd9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tiers_stripe_product_id_key"), "tiers", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("tiers_stripe_product_id_key"),
        "tiers",
        ["stripe_product_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
