"""add tier onboarding mapping

Revision ID: c8d508f52d22
Revises: db9222cca1a3
Create Date: 2026-01-28 15:36:43.329266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8d508f52d22'
down_revision: Union[str, Sequence[str], None] = 'db9222cca1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier_onboarding_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('depends_on_question_id', sa.Integer(), nullable=True),
    sa.Column('depends_on_value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_question_id'], ['onboarding_questions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['onboarding_questions.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_id', 'order', name='uq_tier_order'),
    sa.UniqueConstraint('tier_id', 'question_id', name='uq_tier_question')
    )
    op.create_index(op.f('ix_tier_onboarding_questions_tier_id'), 'tier_onboarding_questions', ['tier_id'], unique=False)
    op.alter_column('onboarding_questions', 'question_type',
               existing_type=postgresql.ENUM('TEXT', 'NUMBER', 'EMAIL', 'PHONE', 'DATE', 'SINGLE_CHOICE', 'MULTI_CHOICE', 'DROPDOWN', 'FILE', name='question_type_enum'),
               nullable=False)
    op.drop_constraint(op.f('onboarding_questions_tier_id_fkey'), 'onboarding_questions', type_='foreignkey')
    op.drop_constraint(op.f('onboarding_questions_depends_on_question_id_fkey'), 'onboarding_questions', type_='foreignkey')
    op.drop_column('onboarding_questions', 'tier_id')
    op.drop_column('onboarding_questions', 'depends_on_value')
    op.drop_column('onboarding_questions', 'order')
    op.drop_column('onboarding_questions', 'depends_on_question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # 1. Add columns as NULLABLE first
    op.add_column('onboarding_questions', sa.Column('depends_on_question_id', sa.INTEGER(), nullable=True))
    op.add_column('onboarding_questions', sa.Column('order', sa.INTEGER(), nullable=True))
    op.add_column('onboarding_questions', sa.Column('depends_on_value', sa.VARCHAR(), nullable=True))
    op.add_column('onboarding_questions', sa.Column('tier_id', sa.INTEGER(), nullable=True))  # nullable first

    # 2. Backfill tier mapping from tier_onboarding_questions
    op.execute("""
        UPDATE onboarding_questions oq
        SET
            tier_id = tq.tier_id,
            "order" = tq."order",
            depends_on_question_id = tq.depends_on_question_id,
            depends_on_value = tq.depends_on_value
        FROM tier_onboarding_questions tq
        WHERE tq.question_id = oq.id;
    """)

    # 3. Now safely make tier_id NOT NULL
    op.alter_column('onboarding_questions', 'tier_id', nullable=False)

    # 4. Restore FKs
    op.create_foreign_key(
        op.f('onboarding_questions_depends_on_question_id_fkey'),
        'onboarding_questions',
        'onboarding_questions',
        ['depends_on_question_id'],
        ['id']
    )

    op.create_foreign_key(
        op.f('onboarding_questions_tier_id_fkey'),
        'onboarding_questions',
        'tiers',
        ['tier_id'],
        ['id']
    )

    # 5. Restore question_type nullable (as before)
    op.alter_column(
        'onboarding_questions',
        'question_type',
        existing_type=postgresql.ENUM(
            'TEXT', 'NUMBER', 'EMAIL', 'PHONE', 'DATE',
            'SINGLE_CHOICE', 'MULTI_CHOICE', 'DROPDOWN', 'FILE',
            name='question_type_enum'
        ),
        nullable=True
    )

    # 6. Drop mapping table
    op.drop_index(op.f('ix_tier_onboarding_questions_tier_id'), table_name='tier_onboarding_questions')
    op.drop_table('tier_onboarding_questions')
