"""add option_id to user_onboarding_answers

Revision ID: db9222cca1a3
Revises: aeb96aba880b
Create Date: 2026-01-28 16:46:42.566100

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db9222cca1a3"
down_revision: str | Sequence[str] | None = "aeb96aba880b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_onboarding_answers", sa.Column("option_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "user_onboarding_answers",
        "onboarding_question_options",
        ["option_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_onboarding_answers", type_="foreignkey")
    op.drop_column("user_onboarding_answers", "option_id")
    # ### end Alembic commands ###
