"""add_stripe_integration

Revision ID: fae09c51fe97
Revises: e849193b3d1c
Create Date: 2026-01-08 16:07:41.396301

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fae09c51fe97"
down_revision: str | Sequence[str] | None = "e849193b3d1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_stripe_customers_id"), "stripe_customers", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_stripe_customers_stripe_customer_id"),
        "stripe_customers",
        ["stripe_customer_id"],
        unique=True,
    )
    op.add_column(
        "subscriptions", sa.Column("stripe_subscription_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "stripe_subscription_id")
    op.drop_index(
        op.f("ix_stripe_customers_stripe_customer_id"), table_name="stripe_customers"
    )
    op.drop_index(op.f("ix_stripe_customers_id"), table_name="stripe_customers")
    op.drop_table("stripe_customers")
    # ### end Alembic commands ###
